# Generated by Django 5.2 on 2025-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20230801_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проекту')),
                ('description', models.TextField(verbose_name='Опис проекту')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Зображення проекту')),
                ('github_link', models.URLField(blank=True, verbose_name='Посилання на GitHub')),
                ('live_link', models.URLField(blank=True, verbose_name='Посилання на живий проект')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок відображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
