# Generated by Django 5.2 on 2025-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_project_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на живий проект'),
        ),
    ]
