# Generated by Django 5.2 on 2025-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_project_github_link_alter_project_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(verbose_name='URL зображення проекту'),
        ),
    ]
